<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <RootNamespace>NuGetMonitor</RootNamespace>
    <AssemblyName>NuGetMonitor</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Controls.DataGrid" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Microsoft.Build.Locator" />
    <PackageReference Include="TomsToolbox.Avalonia" />
    <PackageReference Include="TomsToolbox.Essentials" />
    <PackageReference Include="Fody" PrivateAssets="all" />
    <PackageReference Include="PropertyChanged.Fody" PrivateAssets="all" />
    <PackageReference Include="Throttle.Fody" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NuGetMonitor.Model\NuGetMonitor.Model.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\NugetMonitor.Shared\**\*.cs" Link="%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
