using Microsoft.VisualStudio.Shell;

[assembly: ProvideCodeBase(AssemblyName = "DataGridExtensions")]
[assembly: ProvideCodeBase(AssemblyName = "Microsoft.Extensions.Caching.Abstractions")]
[assembly: ProvideCodeBase(AssemblyName = "Microsoft.Extensions.Caching.Memory")]
[assembly: ProvideCodeBase(AssemblyName = "Microsoft.Extensions.DependencyInjection.Abstractions")]
[assembly: ProvideCodeBase(AssemblyName = "Microsoft.Extensions.Logging.Abstractions")]
[assembly: ProvideCodeBase(AssemblyName = "Microsoft.Extensions.Options")]
[assembly: ProvideCodeBase(AssemblyName = "Microsoft.Extensions.Primitives")]
[assembly: ProvideCodeBase(AssemblyName = "Microsoft.Xaml.Behaviors")]
[assembly: ProvideCodeBase(AssemblyName = "NuGet.Common")]
[assembly: ProvideCodeBase(AssemblyName = "NuGet.Configuration")]
[assembly: ProvideCodeBase(AssemblyName = "NuGet.Frameworks")]
[assembly: ProvideCodeBase(AssemblyName = "NuGet.Packaging")]
[assembly: ProvideCodeBase(AssemblyName = "NuGet.Protocol")]
[assembly: ProvideCodeBase(AssemblyName = "NuGet.Versioning")]
[assembly: ProvideCodeBase(AssemblyName = "NuGetMonitor.Model")]
[assembly: ProvideCodeBase(AssemblyName = "TomsToolbox.Essentials")]
[assembly: ProvideCodeBase(AssemblyName = "TomsToolbox.Wpf")]
[assembly: ProvideCodeBase(AssemblyName = "TomsToolbox.Wpf.Styles")]