name: Release

on: workflow_dispatch

permissions:
  actions: read

env:
  version: '1.7.${{ github.run_number }}'
  repoUrl: ${{ github.server_url }}/${{ github.repository }}
  vsixBuildPath: ${{ github.workspace }}/src/NuGetMonitor/bin/release/net48/NuGetMonitor.vsix
  standaloneBuildPath: ${{ github.workspace }}/src/NuGetMonitor.Standalone/bin/release/net10.0
  publishManifestPath: publish-manifest.json

jobs:
  build:
    name: 🛠️ Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3

      - name: NuGet restore
        run: nuget restore NuGetMonitor.sln

      - name: Build VSIX
        run: msbuild NuGetMonitor.sln /t:Rebuild /p:Configuration=Release
        env:
          DeployExtension: False
          Version: ${{ env.version }}

      - name: Copy VSIX
        run: cp ${{ env.vsixBuildPath }} ${{ github.workspace }}/NuGetMonitor.vsix

      - name: Publish Build Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: NuGetMonitor
          path: |
            NuGetMonitor.vsix
            publish-manifest.json
            readme.md

      - name: Publish Standalone Build Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: NuGetMonitor.Standalone
          path: ${{ env.standaloneBuildPath }}

  release:
    name: 🔖 Tag & Release
    needs: build
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: NuGetMonitor
          path: NuGetMonitor

      - name: Download standalone artifact
        uses: actions/download-artifact@v8
        with:
          name: NuGetMonitor.Standalone
          path: NuGetMonitor.Standalone

      - name: Package NuGetMonitor artifact
        run: Get-ChildItem -Path NuGetMonitor -Recurse -File | Compress-Archive -DestinationPath NuGetMonitor.zip -Force

      - name: Package standalone artifact
        run: Get-ChildItem -Path NuGetMonitor.Standalone -Recurse -File | Compress-Archive -DestinationPath NuGetMonitor.Standalone.zip -Force

      - name: Tag release
        id: tag_release
        uses: mathieudutour/github-tag-action@v6.2
        with:
          custom_tag: '${{ env.version }}'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_release.outputs.new_tag }}
          name: ${{ steps.tag_release.outputs.new_tag }}
          body: ${{ steps.tag_release.outputs.changelog }}
          artifacts: "NuGetMonitor.zip,NuGetMonitor.Standalone.zip"
          skipIfReleaseExists: true

  publishMarketplace:
    name: 🚀 Publish to Marketplace
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: NuGetMonitor

      - name: Publish to Marketplace
        uses: cezarypiatek/VsixPublisherAction@1.2
        with:
          extension-file: NuGetMonitor.vsix
          publish-manifest-file: ${{ env.publishManifestPath }}
          personal-access-code: ${{ secrets.VS_PUBLISHER_ACCESS_TOKEN }}

  publishOpenVSIXGallery:
    needs: build
    name: 🚀 Publish to Open VSIX Gallery
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: NuGetMonitor

      - name: Publish to Open VSIX Gallery
        run: |
            curl -L 'https://www.vsixgallery.com/api/upload?repo=${{ env.repoUrl }}&issuetracker=${{ env.repoUrl }}/issues' -F 'file=@"NuGetMonitor.vsix"'